export const INCREMENT = 'INCREMENT';

export const TOKEN_EXCHANGE_REQUEST = 'TOKEN_EXCHANGE_REQUEST';
export const TOKEN_EXCHANGE_SUCCESS = 'TOKEN_EXCHANGE_SUCCESS';
export const TOKEN_EXCHANGE_FAILURE = 'TOKEN_EXCHANGE_FAILURE';